// src/components/Onboarding/ResumePDF.jsx
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 60,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff',
  },
  header: {
    marginBottom: 30,
    borderBottom: '3px solid #6366f1',
    paddingBottom: 20,
  },
  name: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#1e293b',
    textAlign: 'center',
    marginBottom: 6,
  },
  tagline: {
    fontSize: 14,
    color: '#64748b',
    textAlign: 'center',
    marginBottom: 20,
  },
  section: {
    marginBottom: 28,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4f46e5',
    marginBottom: 10,
    borderLeft: '4px solid #6366f1',
    paddingLeft: 12,
  },
  text: {
    fontSize: 11,
    lineHeight: 1.5,
    color: '#334155',
    marginBottom: 6,
  },
  skillContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  skillPill: {
    fontSize: 10,
    padding: '4px 10px',
    backgroundColor: '#e0f2fe',
    borderRadius: 999,
    color: '#1e40af',
    border: '1px solid #bfdbfe',
  },
  bullet: {
    marginLeft: 20,
    marginBottom: 4,
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 60,
    right: 60,
    textAlign: 'center',
    fontSize: 9,
    color: '#94a3b8',
    borderTop: '1px solid #e2e8f0',
    paddingTop: 12,
  },
});

const ResumePDF = ({ userData }) => (
  <Document>
    <Page size="A4">
      <View style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.name}>{userData?.name || userData?.displayName || 'Your Full Name'}</Text>
          <Text style={styles.tagline}>
            {userData?.targetCareer?.replace('-', ' ').toUpperCase() || 'Aspiring Professional'} • 
            Passionate {userData?.role || 'Learner'} • Seeking Opportunities in Tech
          </Text>
        </View>

        {/* Professional Summary */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Professional Summary</Text>
          <Text style={styles.text}>
            Results-driven {userData?.role || 'professional'} with a strong foundation in {userData?.skills?.slice(0, 4)?.join(', ') || 'modern technologies'}. 
            Targeting a {userData?.targetCareer || 'career path'} role within {userData?.timeline || 'flexible timeframe'}. 
            Committed to continuous learning and delivering high-impact solutions in dynamic environments.
          </Text>
        </View>

        {/* Skills */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Technical Skills</Text>
          <View style={styles.skillContainer}>
            {userData?.skills?.length > 0 ? (
              userData.skills.map((skill, i) => (
                <Text key={i} style={styles.skillPill}>{skill}</Text>
              ))
            ) : (
              <Text style={{ ...styles.text, fontStyle: 'italic', color: '#64748b' }}>
                Skills will appear here once added in your profile
              </Text>
            )}
          </View>
        </View>

        {/* Education */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Education</Text>
          <Text style={styles.text}>
            <Text style={{ fontWeight: 'bold' }}>{userData?.education || 'Degree Level'}</Text>
            {' • '}
            {userData?.institution || 'Institution / Self-Taught'}
          </Text>
        </View>

        {/* Career Goals */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Career Objectives</Text>
          <Text style={styles.text}>• Target Role: {userData?.targetCareer || 'To be defined'}</Text>
          <Text style={styles.text}>• Desired Timeline: {userData?.timeline || 'Flexible'}</Text>
          <Text style={{ ...styles.text, marginTop: 8, fontStyle: 'italic', color: '#64748b' }}>
            Currently following a structured learning roadmap powered by SkillVoyager.AI
          </Text>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text>Generated by SkillVoyager.AI • AI-Powered Career Acceleration Platform</Text>
          <Text style={{ marginTop: 4 }}>www.skillvoyager.ai • Empowering the next generation of tech professionals</Text>
        </View>
      </View>
    </Page>
  </Document>
);

export default ResumePDF;